# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-paginate]
# Permalinks
permalink:        pretty
#relative_permalinks: true
plugins: [jekyll-paginate]

# Setup
title:            sckaiser
tagline:          'homepage'
description:      'Quantum. Lasers. Robots.'
url:              https://www.sckaiser.com
baseurl:          /
# exclude:
#     - node_modules

author:
  name:           'Sarah Kaiser'
  url:            https://sckaiser.com
  email : sckaiser@sckaiser.com
  github : crazy4pi314
  twitter : crazy4pi314

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-168719669-1

# Custom vars
version:          0.0.1

github:
  repo: https://github.com/crazy4pi314/crazy4pi314.github.io

permalink: /blog/:year/:month/:day/:title.html

paginate: 5
paginate_path: "/blog/page:num/"

exclude: ["*.ipynb"]

ga_analytics: UA-168719669-1