# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            sckaiser
tagline:          'homepage'
description:      'Quantum. Lasers. Diamonds.'
url:              http://sckaiser.com
baseurl:          /
exclude:
    - node_modules

author:
  name:           'Sarah Kaiser'
  url:            https://sckaiser.com


# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/poole/hyde
